### ISSUE TITLE
Respawn not working properly

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/SerpentsHand#11]
Sometimes the respawn seems to break during the process, so not all possible players get spawned as Serpent's Hand and CASSIE plays no announcement.

**Comment by DinoNuggets2** [comment]
Yeah, CASSIE doesn't play the announcement when CI spawns either. (I have that set up). I don't know if it's some interference from another plugin or what.

**Comment by FinnFurwolf** [comment]
It never happened again since my comment, so I guess it is fine.
