### ISSUE TITLE
Respawn in Tutorial tower

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/SerpentsHand#15]
Sometimes a player won't get moved to the spawn location and remains in the tower.

**Comment by Marco15453** [comment]
What SerpentsHand Version are you using?

**Comment by FinnFurwolf** [comment]
Wow, that was fast. Thank you!

**Comment by Marco15453** [comment]
np :)

**Comment by FinnFurwolf** [comment]
Bug still exists in 4.1.4
