### ISSUE TITLE
[BUG] No more tags

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/SerpentsHand#17]
**Describe the bug**
Serpent's Hand players have no name or role tag. It only displays the role on the server, like moderator, if they have one.

**To Reproduce**
1. Respawn as Serpent's Hand

**Expected behavior**
Players have their respective name and role tags.

**Serpents Hand Version ("latest" is not a version)**
4.1.3

**Comment by Marco15453** [comment]
Can you provide an server log?

**Comment by Marco15453** [comment]
This bug should be fixed with update 4.1.4

**Comment by FinnFurwolf** [comment]
Bug still exists in 4.1.4

**Comment by FinnFurwolf** [comment]
[Round 2022-01-07 11.26.18.txt](https://github.com/Exiled-Team/SerpentsHand/files/7830230/Round.2022-01-07.11.26.18.txt)

**Comment by Marco15453** [comment]
Do you have an Video that proofs this, i cannot replicate this issue

**Comment by FinnFurwolf** [comment]
![20220108235741_1](https://user-images.githubusercontent.com/43943904/148662920-44934128-8a34-4e66-bfb9-4682cb4179cc.jpg)
Now only the name tag is missing
Maybe this has to do with the new feature of unit names for SH?
