### ISSUE TITLE
[BUG] [A] [ SH] You don't have pe rmission  to execute  this command. Required  pe rmission: sh . spawnteam 

### ISSUE THREAD

**Issue by wumiang** [Exiled-Team/SerpentsHand#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Serpents Hand Version ("latest" is not a version)**
Your Serpents Hand version you are using

**Server Logs**
A clean log from your server logs

**Additional context**

**Comment by wumiang** [comment]
No permissions

**Comment by Marco15453** [comment]
Please use the correct format and fill out correctly
