### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ChinaBuleSky** [Exiled-Team/SerpentsHand#22]
**Describe the bug**
On Exiled 4.2.3

**Screenshots**
![}3 M SI{B3_CR} _$M`0P6](https://user-images.githubusercontent.com/70874019/152649239-204d9406-1a4b-4bca-aeaf-ced09610543f.png)
![V QGMQA7OQJN{%6K8X4CVMD](https://user-images.githubusercontent.com/70874019/152649263-3327d95f-b241-4a2a-bfd6-4d09799a54ee.png)
![4G{C7~NW)5TTGI}QNEEPAM6](https://user-images.githubusercontent.com/70874019/152649290-d273a0d7-b0fa-4c21-b9ec-459afd8114d4.png)

**Comment by Marco15453** [comment]
First of all, please use the correct format
Second that is not a bug, you are missing an assembly/reference
