### ISSUE TITLE
[BUG] Not compatible with Respawn Timer

### ISSUE THREAD

**Issue by Vretu-Dev** [Exiled-Team/SerpentsHand#28]
**Describe the bug**
Serpends Hand respawn show as Chaos

**Comment by Marco15453** [comment]
Do you have a screenshot?

**Comment by Vretu-Dev** [comment]
> Do you have a screenshot?

No but I can send a video if necessary

**Comment by Marco15453** [comment]
Can you send the video?

**Comment by Marco15453** [comment]
Due to no response, this issue is now closed!
