### ISSUE TITLE
[BUG] Auto overcharge doesn't happen

### ISSUE THREAD

**Issue by KittenPixel** [Exiled-Team/SerpentsHand#29]
**Describe the bug**
So when every SCP dies the auto overcharge for 079 doesn't happen
**To Reproduce**
Get a 079 and SCP kill the other SCP not 079, 079's overcharge doesn't happen.

**Expected behavior**
Overcharge happening when all SCPs die

**Serpents Hand Version (v4.4.0)**
Your Serpents Hand version you are using

**Comment by KittenPixel** [comment]
I disabled this plugin and it worked

**Comment by KittenPixel** [comment]
so I want the plugin to work with it correctly

**Comment by Marco15453** [comment]
Are you sure that the Serpends Hands are not alive while all other SCPs are dead?
And the plugin doesn't interact with any of SCP 079 overcharge?

**Comment by KittenPixel** [comment]
yes all serpants hands are dead

**Comment by Marco15453** [comment]
The Plugin doesn't interact with anythign related to the Overcharge
