### ISSUE TITLE
[Suggestion] Option to disable Chaos winning with SCP's

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/SerpentsHand#32]
Could you add an option to enable/disable Chaos winning with SCP's? Currently I need a seperate plugin to disable just this. It would be very helpful to have this combined in one plugin and it would make sense to add this in your plugin, since you have a configurable option, how it should interact with servers, that disabled it.

**Comment by Marco15453** [comment]
If this error still exists, please open a new issue
