### ISSUE TITLE
[BUG] Serpents hands spawn into the void

### ISSUE THREAD

**Issue by spilledsalt** [Exiled-Team/SerpentsHand#39]
Spawning Serpents' hands fall into the void upon spawning (first in a dark room, then slip into the void)

step 1: spawn as serpents hand
step 2: done

**Comment by Marco15453** [comment]
Could you please send me a video of it?

**Comment by spilledsalt** [comment]
[2023-05-01 22-02-42.webm](https://user-images.githubusercontent.com/76984234/235563986-859c3820-1ece-4133-9db4-375ec61a42c7.webm)
here

**Comment by Marco15453** [comment]
You need to change the SpawnPos in the config. It might have changed since then.

**Comment by spilledsalt** [comment]
to what? whats like the spawn pos of chaos?

**Comment by SnivyFilms** [comment]
> to what? whats like the spawn pos of chaos?

I use this for my Serpents Hand Spawns.
      x: 63
      y: 992
      z: -50
This puts the SH spawnwave in the little indent across from the Gate B elevator. Hopefully this helps

**Comment by Marco15453** [comment]
The Spawn Location will be adjusted when the next update releases

**Comment by Marco15453** [comment]
Issue has been fixed
