### ISSUE TITLE
(Enhancement) Better spawning system

### ISSUE THREAD

**Issue by tpd1864blake** [Exiled-Team/SerpentsHand#4]
I don’t think it makes sense from a gameplay perspective for Serpents Hand and Chaos Insurgency to share the same spawn conditions, since CI gains a higher chance of spawning when class-d complete objectives, such as using SCP items, killing scientists, escaping, etc. This encourages Serpents Hand to cooperate with class-d and allow them to escape in order to give them a higher chance to spawn, which doesn’t fit in a lore or gameplay standpoint.

My proposed solution is to include a third respawn ticket system in the plugin. Any time an SCP or Serpents Hand kills somebody, they would gain 1 ticket. In addition, the default ticket count would be low (0-8 or something) meaning SCPs would have to go on a rampage to cause Serpents Hand to spawn, encouraging SCPs to be more aggressive and be much less likely to team with class d. One side effect of less tickets is that SH would likely never spawn on smaller servers, but the plugin is designed for large servers anyways.

This new system would be able to be toggled from the old system, a static percent chance every time CI is spawned, to this new ticket system using a boolean value in the config.

**Pros:**
- Creates more of a divide between Serpents Hand and Chaos Insurgency
- Discourages cross-faction teaming as they cannot rely off of CI spawn tickets
- Helps to break stalemates when CI and MTF keep spawning and are consistently unable to deal significant damage to SCPs

**Cons:**
- Default spawn ticket count would make Serpents Hand less common on small servers (can be mitigated by raising ticket count in config)
- Could lead to situations where SCPs kill an entire respawn wave and gain a significant number of tickets, making it almost guaranteed that SH spawns instead of any other human faction

**Comment by Michal78900** [comment]
This would be hard to implement, but I may consider it. I will probably wait till 11.0 update before I will add any major features to this plugin.
