### ISSUE TITLE
[BUG] Chaos and SCPs still win, even with the config flag for scps_win_with_chaos: false

### ISSUE THREAD

**Issue by SnivyFilms** [Exiled-Team/SerpentsHand#40]
**Describe the bug**
In the config file there is a config to set scps to win with chaos, I have this set to false (under the context that the chaos needs to fight the scps), but in game if Chaos and SCPs are remaining the round will end.

**To Reproduce**
Have an SCP(s) fighting who ever needs to be eliminated. If there is a chaos that spawns, either by a spawn wave or by escaping. When it becomes just SCP v Chaos the game will end.

**Expected behavior**
The round doesn't end, as SCPs and Chaos fights until there is one team remaining.

**Screenshots**
N/A

**Serpents Hand Version ("latest" is not a version)**
Serpents Hand V 5.0.1 Testing Release.
Exiled 6.1.0-rc.1

**Server Logs**
[Round 2023-05-01 04.32.01.txt](https://github.com/Exiled-Team/SerpentsHand/files/11368597/Round.2023-05-01.04.32.01.txt)

**Additional context**
If the logs attached isn't what you're looking for, let me know so I can look for the correct logs.

**Comment by SnivyFilms** [comment]
I went to test the bug fix with SH V 5.0.2 Testing release, still doesn't work. SCPs and Chaos will have the round end if both are alive.
Attached is the server log of the round that was played to test it
[Round 2023-05-02 22.58.39.txt](https://github.com/Exiled-Team/SerpentsHand/files/11378283/Round.2023-05-02.22.58.39.txt)
The following is the config that I have.

serpents_hand:
  # Whether or not the plugin is enabled
  is_enabled: true
  # Whether or not debug messages will be shown
  debug: false
  # Options for Serpents Hand players
  serpents_hand_modifiers:
    # Determines role name seen ingame (Supports Colors)
    role_name: Serpent's Hand
    # The amount of health Serpents Hand has.
    health: 100
    # The items Serpents Hand spawn with. (supports CustomItems)
    spawn_items:
    - GunCrossvec
    - KeycardChaosInsurgency
    - GrenadeFlash
    - Radio
    - Medkit
    - ArmorCombat
    # The ammo Serpents Hand spawn with.
    spawn_ammo:
      Nato556: 0
      Nato762: 40
      Nato9: 120
      Ammo12Gauge: 0
      Ammo44Cal: 0
    # Determines if friendly fire between Serpents Hand and SCPs is enabled
    friendly_fire: false
    # Determines if Serpents Hand should teleport to SCP-106 after exiting his pocket dimension
    teleport_to106: true
    # Determines if Serpents Hand should be killed within the pocket dimension when the warhead detonates.
    warhead_kills_in_pocket: true
    # Set this to false if Chaos and SCPs CANNOT win together on your server
    scps_win_with_chaos: false
  # Options for Serpents Hand spawn
  spawn_manager:
    # The chance for Serpents Hand to spawn instead of Chaos.
    spawn_chance: 25
    # The maximum size of a Serpents Hand squad.
    max_squad: 8
    # How many respawn waves must occur before considering Serpents Hand to spawn.
    respawn_delay: 1
    # The maximum number of times Serpents can spawn per game.
    max_spawns: 1
    # Determines if Serpents Hand should be able to spawn when there is no SCPs.
    can_spawn_without_scps: false
    # The message annouced by CASSIE when Serpents hand spawn. (Empty = Disabled)
    entry_annoucement: pitch_1 MTFUNIT .g3 Epsilon pitch_0.5 11 pitch_1 .g4 pitch_0.2 designated yield_3 pitch_1 Unknown .g6 Group of .g2 Interest detected in surface zone
    # The message annouced by CASSIE when Chaos spawn. (Empty = Disabled)
    chaos_entry_annoucement: 
    # The broadcast sent to Serpents Hand when they spawn.
    spawn_broadcast:
      # The broadcast content
      content: <size=30>\n<color=#01FB57>[SERPENTS HAND]</color>\n<color=#C0C0C0>You are <color=#FFFFFF>Serpents Hand</color><color=#C0C0C0>! Work with <color=#FFFFFF>SCP</color><color=#C0C0C0>s, and kill all other targets!</color></size>
      # The broadcast duration
      duration: 10
      # The broadcast type
      type: Normal
      # Indicates whether the broadcast should be shown or not
      show: true
    # The broadcast shown to SCPs when the Serpents Hand respawns.
    entry_broadcast:
      # The broadcast content
      content: <size=30>\n<color=#01FB57>[SERPENTS HAND]</color>\n<color=#FFFFFF>Serpents Hand</color><color=#C0C0C0> has spawned!</color>
      # The broadcast duration
      duration: 10
      # The broadcast type
      type: Normal
      # Indicates whether the broadcast should be shown or not
      show: true
    # The Serpents Hand spawn position.
    spawn_pos:
      x: 63
      y: 992
      z: -50

Hopefully this helps with getting this bug fixed

**Comment by SnivyFilms** [comment]
Regarding SH 5.0.3 Testing Release it is STILL broken with Chaos and SCPs still ending if both are alive. Apologies

**Comment by Marco15453** [comment]
Sorry for the late response, I added some debugging, I can't test it right now

Please use the file below (you need to extract it because i can't upload the .dll directly
[SerpentsHand.zip](https://github.com/Exiled-Team/SerpentsHand/files/11642610/SerpentsHand.zip)

**Comment by Marco15453** [comment]
Could you also please send me a list of your plugins?

**Comment by SnivyFilms** [comment]
> Could you also please send me a list of your plugins?

Total number of plugins: 19
                                 Enabled plugins: 17
                                 Disabled plugins: 2
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 Common Utilities:
                                        - Author: Joker119
                                        - Version: 7.0.3.0
                                        - Required Exiled Version: 7.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Higher
                                 UIURescueSquad:
                                        - Author: JesusQC, Michal78900, maintained by Marco15453
                                        - Version: 4.1.3
                                        - Required Exiled Version: 7.0.0
                                        - Prefix: UIURescueSquad
                                        - Priority: Medium
                                 Custom Unit:
                                        - Disabled
                                        - Author: VALERA771#1471
                                        - Version: 2.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: CustomUnit
                                        - Priority: Medium
                                 CandyWeight:
                                        - Author: Build
                                        - Version: 3.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: CandyWeight
                                        - Priority: Medium
                                 Serpents Hand:
                                        - Author: yanox, Michal78900 and Marco15453
                                        - Version: 5.0.3
                                        - Required Exiled Version: 6.1.0
                                        - Prefix: serpents_hand
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 ScpSwap:
                                        - Author: DentyTxR
                                        - Version: 1.1.3
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: ScpSwap
                                        - Priority: Medium
                                 NukeLock:
                                        - Author: Marco15453
                                        - Version: 1.11.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: nuke_lock
                                        - Priority: Medium
                                 MvpUtility:
                                        - Disabled
                                        - Author: Undid-Iridium
                                        - Version: 2.0.1
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: mvp_utility
                                        - Priority: Medium
                                 CustomRoles:
                                        - Author: Galaxy119
                                        - Version: 5.0.3.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: CustomRoles
                                        - Priority: Medium
                                 CustomItems:
                                        - Author: Exiled-Team
                                        - Version: 7.0.3.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: custom_items
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.2.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Joker119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 7.0.0.0
                                        - Required Exiled Version: 7.0.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 BetterSinkholes2:
                                        - Author: warden161 (original by blackruby)
                                        - Version: 1.1.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: better_sinkholes2
                                        - Priority: Medium
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 4.0.1
                                        - Required Exiled Version: 7.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Lowest




> Sorry for the late response, I added some debugging, I can't test it right now
> 
> Please use the file below (you need to extract it because i can't upload the .dll directly [SerpentsHand.zip](https://github.com/Exiled-Team/SerpentsHand/files/11642610/SerpentsHand.zip)

Sure thing, I'll let you know how it goes

**Comment by SnivyFilms** [comment]
> > Could you also please send me a list of your plugins?
> 
> Total number of plugins: 19 Enabled plugins: 17 Disabled plugins: 2
> 
> ```
>                              Exiled.Events:
>                                     - Author: Exiled Team
>                                     - Version: 7.0.0.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_events
>                                     - Priority: Highest
>                              Common Utilities:
>                                     - Author: Joker119
>                                     - Version: 7.0.3.0
>                                     - Required Exiled Version: 7.0.0
>                                     - Prefix: CommonUtilities
>                                     - Priority: Higher
>                              UIURescueSquad:
>                                     - Author: JesusQC, Michal78900, maintained by Marco15453
>                                     - Version: 4.1.3
>                                     - Required Exiled Version: 7.0.0
>                                     - Prefix: UIURescueSquad
>                                     - Priority: Medium
>                              Custom Unit:
>                                     - Disabled
>                                     - Author: VALERA771#1471
>                                     - Version: 2.0.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: CustomUnit
>                                     - Priority: Medium
>                              CandyWeight:
>                                     - Author: Build
>                                     - Version: 3.0.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: CandyWeight
>                                     - Priority: Medium
>                              Serpents Hand:
>                                     - Author: yanox, Michal78900 and Marco15453
>                                     - Version: 5.0.3
>                                     - Required Exiled Version: 6.1.0
>                                     - Prefix: serpents_hand
>                                     - Priority: Medium
>                              Exiled.CustomRoles:
>                                     - Author: Exiled Team
>                                     - Version: 7.0.0.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_custom_roles
>                                     - Priority: Medium
>                              ScpSwap:
>                                     - Author: DentyTxR
>                                     - Version: 1.1.3
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: ScpSwap
>                                     - Priority: Medium
>                              NukeLock:
>                                     - Author: Marco15453
>                                     - Version: 1.11.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: nuke_lock
>                                     - Priority: Medium
>                              MvpUtility:
>                                     - Disabled
>                                     - Author: Undid-Iridium
>                                     - Version: 2.0.1
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: mvp_utility
>                                     - Priority: Medium
>                              CustomRoles:
>                                     - Author: Galaxy119
>                                     - Version: 5.0.3.0
>                                     - Required Exiled Version: 5.0.0
>                                     - Prefix: CustomRoles
>                                     - Priority: Medium
>                              CustomItems:
>                                     - Author: Exiled-Team
>                                     - Version: 7.0.3.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: custom_items
>                                     - Priority: Medium
>                              Exiled.Permissions:
>                                     - Author: Exiled Team
>                                     - Version: 7.0.0.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_permissions
>                                     - Priority: Medium
>                              Exiled.Updater:
>                                     - Author: Exiled.Updater
>                                     - Version: 3.1.2.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_updater
>                                     - Priority: Medium
>                              Admin Tools:
>                                     - Author: Originally by Joker119. Modifications by KoukoCocoa & Thomasjosif
>                                     - Version: 6.0.0.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: AT
>                                     - Priority: Medium
>                              Exiled.CreditTags:
>                                     - Author: Babyboucher20 & iRebbok & Exiled Team
>                                     - Version: 7.0.0.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_credits
>                                     - Priority: Medium
>                              Exiled.CustomItems:
>                                     - Author: Exiled Team
>                                     - Version: 7.0.0.0
>                                     - Required Exiled Version: 7.0.0.0
>                                     - Prefix: exiled_custom_items
>                                     - Priority: Medium
>                              BetterSinkholes2:
>                                     - Author: warden161 (original by blackruby)
>                                     - Version: 1.1.0
>                                     - Required Exiled Version: 6.0.0
>                                     - Prefix: better_sinkholes2
>                                     - Priority: Medium
>                              RespawnTimer:
>                                     - Author: Michal78900
>                                     - Version: 4.0.1
>                                     - Required Exiled Version: 7.0.0
>                                     - Prefix: respawn_timer
>                                     - Priority: Lowest
> ```
> 
> > Sorry for the late response, I added some debugging, I can't test it right now
> > Please use the file below (you need to extract it because i can't upload the .dll directly [SerpentsHand.zip](https://github.com/Exiled-Team/SerpentsHand/files/11642610/SerpentsHand.zip)
> 
> Sure thing, I'll let you know how it goes

End Conditions is in there as well, but I'll disable it to test it

**Comment by Marco15453** [comment]
Alright, be sure that End Conditions does not interrupt with the SerpentsHand Conditions

**Comment by SnivyFilms** [comment]
I am having trouble compiling the plugin on my end. Visual Studio is sharing these errors specifically.
![image](https://github.com/Exiled-Team/SerpentsHand/assets/120346554/df44049f-0a40-4e69-b28e-7a8ab4c287b8)

**Comment by Marco15453** [comment]
Why do you want to compile it on your end?

**Comment by Marco15453** [comment]
The Patches on the old version is no longer used.
Those can be removed.

**Comment by SnivyFilms** [comment]
> Why do you want to compile it on your end?

Because I downloaded the wrong thing lmao, mbad.

>

> The Patches on the old version is no longer used. Those can be removed.

Alright

**Comment by SnivyFilms** [comment]
I have tested it and the flag still doesn't work. I enabled Debugging to the console, which is what is provided below.

[2023-06-03 17:44:58.988 +00:00] [DEBUG] [SerpentsHand] OnEndingRound - mtfAlive: False | ciAlive: False | scpAlive: True | dclassAlive: True | scientistsAlive: False | shAlive: False
[2023-06-03 17:44:59.000 +00:00] [DEBUG] [SerpentsHand] OnEndingRound If Statement Debugging - True | False
[2023-06-03 17:45:01.543 +00:00] [DEBUG] [SerpentsHand] OnEndingRound - mtfAlive: False | ciAlive: True | scpAlive: True | dclassAlive: False | scientistsAlive: False | shAlive: False
[2023-06-03 17:45:01.556 +00:00] [DEBUG] [SerpentsHand] OnEndingRound If Statement Debugging - True | False
[2023-06-03 17:45:01.568 +00:00] Round finished! Anomalies: 1 | Chaos: 1 | Facility Forces: 0 | D escaped percentage: 0 | S escaped percentage: : 1

**Comment by Marco15453** [comment]
It should been fixed with the newest update.
