### ISSUE TITLE
Does not work with the latest Exiled/SL Version

### ISSUE THREAD

**Issue by funniman-exe** [Exiled-Team/SerpentsHand#46]
Not Really a Bug but has been annoying me ever since i updated sl and exiled. Neither SerpentsHand nor [RespawnTimer](https://github.com/Michal78900/RespawnTimer) work now. They both throw a TypeLoadException while enabling:
`Plugin "Serpents Hand" threw an exception while enabling: System.TypeLoadException: Could not resolve type with token 01000041 from typeref (expected class 'CustomEventHandler' in assembly '')
                                   at Exiled.Loader.Loader.EnablePlugins () [0x000c6] in <e50966ad59b94987b8c6651c9f3d0ecb>:0`
Can someone fix this or at least give me reassurance that the plugin will be updated to fix this?

**Comment by Max21233** [comment]
Doesn't work, can confirm, does anyone have a way to fix this?

**Comment by SnivyFilms** [comment]
Check the fork I made

**Comment by Marco15453** [comment]
**This has been fixed in the latest update *v6.3.1***
