### ISSUE TITLE
Compatibility with SCP-035

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/SerpentsHand#5]
Would be nice to have it compatible with SCP-035 or a config option to disable round end handling by this plugin.

**Comment by Michal78900** [comment]
The plugin should be comaptible with SCP-035

**Comment by FinnFurwolf** [comment]
Ok, then I probably found a bug. The round won't end, if you have Serpents Hand and SCP-035 alive.
I tried a few things and I am pretty sure that your plugin is blocking the round to end.
I disabled round end handling in SCP-035 and endconditions plugin, I am using as well, is correctly configured.
Serpents Hand seems to count SCP-035 as target if it is dboy, mtf, etc.
